
name: Build ZiggaTel OpenWRT

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib git libncurses5-dev libssl-dev python3-distutils \
            zlib1g-dev libelf-dev wget python3 unzip rsync

      - name: Clone OpenWRT
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout v23.05.2
          cp -r ../* openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: ZiggaTel-Firmware
          path: openwrt/bin/targets/
